env                   = "dev"
resource_group_name   = "my-webapp-rg-dev"
acr_name              = "mywebappacrdev"
aci_name              = "mywebappacidev"
container_name        = "flaskappdev"
location              = "CentralIndia"
acr_repo              = "flask-app"