name: Deploy Flask App to Azure  # ✅ Fixing invalid workflow name

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment for Deployment (dev, prod, etc.)'
        required: true
        default: 'dev'
      action:
        description: 'Action to perform (deploy, destroy)'
        required: true
        default: 'deploy'
      step:
        description: 'Deployment Step (resource-group, acr, push-image, aci)'
        required: false
        default: 'all'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get ACR Name from Terraform  # ✅ Fixed indentation & syntax
        if: github.event.inputs.action == 'deploy' && (github.event.inputs.step == 'push-image' || github.event.inputs.step == 'all')
        working-directory: terraform
        run: |
          ACR_NAME=$(terraform output -raw acr_name)
          echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
          echo "Retrieved ACR_NAME: $ACR_NAME"