name: Terraform Plan Check

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI test

jobs:
  terraform:
    runs-on: ubuntu-latest  # You can change to self-hosted if needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Use your required Terraform version

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Verify Terraform Plan
        run: terraform plan -var-file=terraform.tfvars