name: Create ACI  # <-- Corrected workflow name

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login using Service Principal
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true

  aci:
    runs-on: ubuntu-latest
    needs: login  # Ensures Azure login runs first
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetches Terraform files

      - name: Debug - List Files
        run: ls -R  # Ensure Terraform files exist in the runner

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Set environment variables for Terraform authentication
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Initialize Terraform Backend
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TFSTATE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.TFSTATE_CONTAINER }}" \
            -backend-config="key=terraform.tfstate"

      - name: Validate Terraform Configuration
        working-directory: terraform
        run: terraform validate

      - name: Plan Terraform Deployment
        working-directory: terraform
        run: terraform plan -var-file="env/dev.tfvars" -out=tfplan

      - name: Extract ACR Name from Terraform Output
        working-directory: terraform
        run: |
          ACR_NAME=$(grep '^acr_name' env/dev.tfvars | awk -F '=' '{print $2}' | tr -d ' "')
          echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
          echo "Extracted ACR Name: $ACR_NAME"

      - name: Apply Terraform to Deploy ACI
        working-directory: terraform
        run: terraform apply -auto-approve -target=azurerm_container_group.aci -var-file="env/dev.tfvars"  # Change "dev" if needed