name: Deploy Flask App to Azure

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment for Deployment (dev, prod, etc.)'
        required: true
        default: 'dev'
      action:
        description: 'Action to perform (deploy, destroy)'
        required: true
        default: 'deploy'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Debug - List Files
      - name: Debug - List Files
        run: ls -lR

      # Step 3: Login to Azure using OIDC
      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      # Step 4: Cache Docker layers (Only for Deploy)
      - name: Cache Docker layers
        if: github.event.inputs.action == 'deploy'
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache  
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 5: Log in to Azure Container Registry (Only for Deploy)
      - name: Log in to Azure Container Registry
        if: github.event.inputs.action == 'deploy'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 6: Build and Push Docker Image (Only for Deploy)
      - name: Build and Push Docker Image
        if: github.event.inputs.action == 'deploy'
        run: |
          docker buildx build --cache-from=type=registry,ref=${{ secrets.ACR_NAME }}.azurecr.io/flask-app:latest \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:${{ github.sha }} \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:latest

      # Step 7: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      # Step 8: Set environment variables for Terraform authentication
      - name: Set environment variables for Terraform authentication
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      # Step 9: Initialize Terraform Backend
      - name: Initialize Terraform Backend
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TFSTATE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.TFSTATE_CONTAINER }}" \
            -backend-config="key=terraform.tfstate"

      # Step 10: Validate Terraform Configuration
      - name: Validate Terraform Configuration
        working-directory: terraform
        run: terraform validate

      # Step 11: Conditional Deploy/Destroy Step
      - name: Terraform Plan & Apply or Destroy
        working-directory: terraform
        run: |
          if [[ "${{ github.event.inputs.action }}" == "deploy" ]]; then
            terraform plan -out=tfplan -var="client-id=${{ secrets.ARM_CLIENT_ID }}" -var="client-secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="tenant-id=${{ secrets.ARM_TENANT_ID }}" -var="subscription-id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var-file="env/${{ github.event.inputs.env }}.tfvars"
            terraform apply -auto-approve tfplan
          elif [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            terraform destroy -auto-approve -var="client-id=${{ secrets.ARM_CLIENT_ID }}" -var="client-secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="tenant-id=${{ secrets.ARM_TENANT_ID }}" -var="subscription-id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var-file="env/${{ github.event.inputs.env }}.tfvars"
          else
            echo "Invalid action: ${{ github.event.inputs.action }}"
            exit 1
          fi

      # Step 12: Deploy Flask App to Azure Container Instance (ACI) (Only for Deploy)
      - name: Deploy Flask App to ACI
        if: github.event.inputs.action == 'deploy'
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          location: CentralIndia
          name: flask-app-${{ github.event.inputs.env }}
          image: ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:latest
          cpu: 1
          memory: 1.5
          environment-variables: |
            ENVIRONMENT=${{ github.event.inputs.env }}
          dns-name-label: flask-app-${{ github.event.inputs.env }}
          ports: 80

      # Step 13: Show Terraform Outputs (Only for Deploy)
      - name: Show Terraform Outputs
        if: github.event.inputs.action == 'deploy'
        run: terraform output
        working-directory: terraform