name: Deploy Flask App to Azure

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment for Deployment (dev, prod, etc.)'
        required: true
        default: 'dev'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Debug - List Files
      - name: Debug - List Files
        run: ls -lR

      # Step 3: Login to Azure using OIDC
      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      # Step 4: Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache  # Cache location for Docker layers
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 5: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 6: Build and Push Docker Image (without cache export)
      - name: Build and Push Docker Image
        run: |
          docker buildx build --cache-from=type=registry,ref=${{ secrets.ACR_NAME }}.azurecr.io/flask-app:latest \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:latest

      # Step 7: Deploy Flask App to Azure Container Instance (ACI)
      - name: Deploy Flask App to ACI
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}  # The Azure resource group name
          name: flask-app  # The name of the container in ACI
          image: ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:latest  # The image to deploy from ACR
          cpu: 1  # CPU for the container
          memory: 1.5  # Memory for the container
          environment-variables: |
            ENVIRONMENT=${{ github.event.inputs.env }}  # Environment variable for Flask app
          dns-name-label: flask-app-${{ github.event.inputs.env }}  # DNS name for public access
          ports: 80  # Exposing port 80 for the app

      # Step 8: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      # Step 9: Set environment variables for Terraform authentication
      - name: Set environment variables for Terraform authentication
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      # Step 10: Debug - Print Environment Variables (for troubleshooting)
      - name: Debug - Print Environment Variables
        run: |
          echo "ARM_CLIENT_ID=$ARM_CLIENT_ID"
          echo "ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET"
          echo "ARM_TENANT_ID=$ARM_TENANT_ID"
          echo "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID"

      # Step 11: Initialize Terraform Backend
      - name: Initialize Terraform Backend
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TFSTATE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.TFSTATE_CONTAINER }}" \
            -backend-config="key=terraform.tfstate"

      # Step 12: Validate Terraform Configuration
      - name: Validate Terraform Configuration
        working-directory: terraform
        run: terraform validate

      # Step 13: Plan Terraform Deployment
      - name: Plan Terraform Deployment
        working-directory: terraform
        run: terraform plan -out=tfplan -var="client-id=${{ secrets.ARM_CLIENT_ID }}" -var="client-secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="tenant-id=${{ secrets.ARM_TENANT_ID }}" -var="subscription-id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var-file="env/${{ github.event.inputs.env }}.tfvars"

      # Step 14: Apply Terraform Deployment
      - name: Apply Terraform Deployment
        working-directory: terraform
        run: terraform apply -auto-approve tfplan