name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repo is pulled

      - name: Debug - List Files
        run: ls -lR  # Check if Terraform files exist

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Initialize Terraform
        run: terraform init \
          -backend-config="resource_group_name=${{ secrets.TFSTATE_RESOURCE_GROUP }}" \
          -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.TFSTATE_CONTAINER }}" \
          -backend-config="key=terraform.tfstate"
        working-directory: terraform  # Ensure Terraform runs from correct folder

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform  # Ensure Terraform runs from correct folder

      - name: Plan Terraform
        run: terraform plan -out=tfplan \
          -var-file="env/dev.tfvars"  # Change for other environments
        working-directory: terraform  # Ensure Terraform runs from correct folder

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
        working-directory: terraform  # Ensure Terraform runs from correct folder