name: Create Resource Group

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (dev, uat, prod)'
        required: true
        default: 'dev'

permissions:
  id-token: write
  contents: read

jobs:
  create-resource-group:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Initialize Terraform
        run: |
          terraform init -backend-config="storage_account_name=${{ secrets.TFSTATE_ACCOUNT_NAME }}" -backend-config="container_name=tfstate" -backend-config="key=rg.tfstate"

      - name: Apply Terraform (Resource Group)
        run: |
          terraform apply -var-file="envs/${{ github.event.inputs.environment }}/terraform.tfvars"
